/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.{html,js}", "./!(build|dist|.*)/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        ghostwhite: "#fafbff",
        black: "#000",
        whitesmoke: "#f5f6f8",
        white: "#fff",
        "pallet-3-primary": "#4f46ba",
        slategray: {
          "100": "#757095",
          "200": "#64607d",
        },
        mediumseagreen: "#22d497",
        "pallet-4-primary": "#3734a9",
        darkslategray: "#454545",
        silver: "#c4c4c4",
        "pallet-4-tone": "#fdbc64",
        gainsboro: {
          "100": "#e5e5ea",
          "200": "#dbe4e9",
        },
        "pallet-4-accent": "#ff7f5c",
        "text-light": "#718ebf",
        "pallet-4-grey": "#e8f2ff",
        "pallet-4-secondary": "#00e1f0",
        aliceblue: "#dbf1fa",
        lightblue: {
          "100": "#c9e7f2",
          "200": "#abc8d2",
        },
        lightgray: "#cfcfcf",
        "pallet-1-dark": "#1b1c31",
        gray: "#181433",
        lavender: "#eeeeff",
      },
      spacing: {},
      fontFamily: {
        manrope: "Manrope",
        gilroy: "Gilroy",
        "gilroy-semibold": "Gilroy-SemiBold",
      },
      borderRadius: {
        "28xl": "47px",
        xl: "20px",
        "11xl": "30px",
        "3xs": "10px",
        "8xs-2": "4.2px",
        "12xs": "1px",
      },
    },
    fontSize: {
      "3xl": "22px",
      xl: "20px",
      sm: "14px",
      mid: "17px",
      base: "16px",
      mini: "15px",
      "37xl": "56px",
      "11xl": "30px",
      "31xl": "50px",
      lg: "18px",
      lgi: "19px",
      "xs-1": "11.1px",
      "52xl": "71px",
      "6xl": "25px",
      "53xl": "72px",
      "10xl": "29px",
      "2xl": "21px",
      inherit: "inherit",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
